# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://Kanimozhi:Kani1012%2A@cluster0.7ytdo9n.mongodb.net/invoicedb?retryWrites=true&w=majority

# The default database your Spring Boot app will use
spring.data.mongodb.database=invoicedb

# Optional: increase connection timeout (milliseconds)
spring.data.mongodb.connection-timeout=30000

# Optional: set server selection timeout (milliseconds)
spring.data.mongodb.server-selection-timeout=30000

# Optional: SSL enabled (required by Atlas)
spring.data.mongodb.ssl.enabled=true

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a339d4001@smtp-brevo.com
spring.mail.password=bskheAtqoo1H7Ji
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.from=kanimozhiparthiban12@gmail.com

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

clerk.issuer=https://refined-shad-13.clerk.accounts.dev
clerk.jwks.url=https://refined-shad-13.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_/A9qcBTpVCS4QSL39U2EsSwQAcBdifpf

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
